
- name: Making Directory for Download Files
  file:
    path: ~/prometheus
    state: directory

- name: Download/Extract Prometheus Files
  unarchive:
    src: "{{source}}"
    dest: ~/prometheus
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Prometheus Executables Files Added
  shell: |
    cd ~/prometheus/prometheus*
    cp -r . /usr/local/bin/prometheus

- name: Prometheus Service File Copy
  copy:
    src: prometheus.service
    dest: /etc/systemd/system
    mode: 777
    owner: root
    group: root

- name: Verifying Prometheus
  service:
    name: prometheus
    state: restarted
    enabled: true
